upgrade XRP to XRPL
bitpay/crypto-rpc pull request #167
Opened 2022-12-06 15:27 UTC by nitsujlangston

2022-12-06 17:50 UTC, escottalexander submitted a review, later dismissed
LGTM. I like all the added try/catchs and the additional tests. Everything looks a lot cleaner than before as well.

2022-12-06 17:50 UTC, escottalexander commented on tests/xrp.js
> +    // await xrpRPC.asyncRequest('ledger_accept');
This comment can be removed.

2022-12-06 18:05 UTC, nitsujlangston commented on tests/xrp.js
> +    // await xrpRPC.asyncRequest('ledger_accept');
thanks, fixed and pushed

2022-12-07 15:04 UTC, escottalexander approved these changes
This looks good. Re-ran the tests in docker and confirmed that everything works with the new version.

2022-12-07 23:57 UTC, kajoseph commented
@nitsujlangston Why did you add the try catches in the tests? A throw will fail the test anyway and usually with a more helpful error than `expected ... to not exist`

2022-12-13 15:51 UTC, kajoseph requested changes
Just have one thing to fix. I'm still trying to understand something with the amounts. According to the docs, I should be able to create a new account with only 10+ XRP, but I tried with 100 XRP and it didn't work. It worked with 1000 XRP and I don't know why.

tl;dr - I'm still trying to make sure the `amount` handling is correct in sendTransaction

2022-12-13 19:33 UTC, kajoseph approved these changes
tACK

2022-12-13 19:56 UTC, merged